[package]
name = "schedule-service"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.11.0"
prost = "0.12"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
once_cell = "1.19.0"

[build-dependencies]
tonic-build = "0.11.0"