-- Data we are getting events from
-- ,,,,,,1°giorno,2°giorno,,,NOMINATIVI ESTERNI
-- ZONA,PIANO ,Aula,n.Alunni,Attività,,22/2/2024,23/2/2024,,LEGENDA,
-- Terra Ovest,Piano Terra Rialzato,05-TW,23,"Dibattito immigrazione, problema o opportunità? ",,XX,XX,,DIBATTITI,
-- Terra Ovest,Piano Terra Rialzato,07-TW,22,Dibattito inclusività e diversità,,XX,XX,,MUSICA,
-- Terra Ovest,Piano Terra Rialzato,09-TW,26,Dibattito giocatori di calcio,,XX,XX,,STUDIO,
-- Terra Ovest,Piano Terra Rialzato,12-TW,25,Dibattito sul progresso tecnologico,,XX,XX,,FILM,
-- Terra Ovest,Piano Terra Rialzato,14-TW,22,Dibattito politico,,XX,XX,,GIOCHI,
-- Terra Ovest,Piano Terra Rialzato,16-TW,22,Dibattito guerra israelo-palestinese,,XX,XX,,SPORT,
-- Terra Ovest,Piano Terra Rialzato,18-TW,25,Dibattito guerra Ucraina-Russia,,XX,XX,,LEZIONI,
-- ,,,,,,,,,XX = 2 TURNI,
-- Ovest,Primo Piano,07-1W,20,Aula studio maturandi 1,,XX,XX,,X = 1 TURNO,
-- Ovest,Primo Piano,13-1W,20,Aula studio maturandi 2,,XX,XX,,inizio attività forum ore 8.30,
-- ,,,,,,,,,fine attività forum ore 13.00 ,
-- Ovest,Secondo Piano,08-2W,18,"Film ""Il buco""",,XX,XX,proiettore,ricreazione di 20 minuti,
-- Ovest,Secondo Piano,10-2W,21,"Giochi di carte, porta un mazzo e si fa un torneo 1",,XX,XX,,durata di ogni turno = 2 ore ,
-- Ovest,Secondo Piano,12-2W,21,"Giochi di carte, porta un mazzo e si fa un torneo 2",,XX,XX,,appello dalle 8.00 alle 8.30,
-- Ovest,Secondo Piano,14-2W,26,Lezione di produzione musicale,,XX,XX,,contro appello dalle 12.50 alle 13.10,studente Meucci
-- ,,,,,,,,,,
-- Terra Centrale,Piano Terra Rialzato,corridoio,25,Muri creativi,,XX,XX,,,educativa di strada Q4 Firenze
-- Terra Centrale,Piano Terra Rialzato,01-TC,28,"Lezione Vab, (Vigilanza Antincendi boschivi), come farne parte",,X,X,proiettore e parcheggio mezzi,,
-- Terra Centrale,Piano Terra Rialzato,07-TC,22,"Enogastronomia, porta del cibo e lo gustiamo insieme",,XX,XX,,,
-- Terra Centrale,Piano Terra Rialzato,09-TC,26,"Videogiochi, porta un videogioco e ci divertiamo insieme",,XX,XX,,,
-- Terra Centrale,Piano Terra Rialzato,11-TC,24,Lezione su sfruttamento ambientale ed animale,,,XX,proiettore,,Donato
-- Terra Centrale,Piano Terra Rialzato,13-TC,35,Lezione Machine learning,,,X,"proiettore, solo primo turno",,Giulia Martini
-- Terra Centrale,Piano Terra Rialzato,13-TC,16,Arti marziali miste teorico e pratico ,,X,X,"tappetini, solo secondo turno",,Jacopo Giunti
-- ,,,,,,,,,,
-- Terra Est,Piano Terra Rialzato,08-TE,26,Lezione di scrittura barre musicali,,XX,XX,,,educativa di strada Q4 Firenze
-- ,,,,,,,,,,
-- Est,Primo Piano,00-1E,28,"Film ""Rush""",,XX,XX,proiettore,,
-- Est,Primo Piano,01-1E,28,Torneo di FIFA,,XX,XX,proiettore,,
-- Est,Primo Piano,06-1E,28,"Film ""The Truman show""",,XX,XX,proiettore,,
-- Est,Primo Piano,07-1E,28,"Film ""Il bambino con il pigiama a righe""",,XX,XX,proiettore ,,
-- Est,Primo Piano,08-1E,28,Laboratorio di strumenti musicali,,,,in attesa ...,,in attesa...
-- Est,Primo Piano,09-1E,28,Giochi da tavolo ,,XX,XX,,,
-- Est,Primo Piano,10-1E,26,Torneo di scacchi 2,,XX,XX,,,
-- Est,Primo Piano,11-1E,25,Aula di scrittura o lettura ,,XX,XX,,,
-- Est,Primo Piano,12-1E,28,"Film ""L'attimo fuggente""",,XX,XX,proiettore,,
-- Est,Primo Piano,13-1E,26,"Aula powernap, riposati e recupera le energie",,XX,XX,,,
-- ,,,,,,,,,,
-- Est,Secondo Piano,02-2E,22,"Scrittura basi musicali, imparare le note",,XX,XX,,,educativa di strada Q4 Firenze
-- Est,Secondo Piano,03-2E,26,Aula studio non maturandi 1,,XX,XX,,,
-- Est,Secondo Piano,04-2E,26,Lezione presentazione progetto macchina fotografica ,,X,X,proiettore,,prof. Cautiero
-- Est,Secondo Piano,06-2E,26,Lezione sui motori,,X,X,proiettore,,2 studenti meucci
-- Est,Secondo Piano,08-2E,26,"Film ""Non ci resta che piangere""",,XX,XX,proiettore,,
-- Est,Secondo Piano,09-2E,26,Aula studio non maturandi 2,,XX,XX,,,
-- Est,Secondo Piano,10-2E,26,Lezione contro la violenza sulle donne,,,,in attesa ,,
-- Est,Secondo Piano,11-2E,27,Dibattito sulla legalizzazione o meno delle droghe leggere,,XX,XX,,,
-- Est,Secondo Piano,12-2E,28,Lezione anime,,XX,XX,,,Niccolò Battistini (ex. studente)
-- Est,Secondo Piano,13-2E,27,"Lezione su Bitcoin, Blockchain e Cryptovalute",,,,in attesa ,,
-- Est,Secondo Piano,14-2E,28,Aula studio non maturandi 3,,XX,XX,,,
-- Est,Secondo Piano,15-2E,26,"Film ""Billy Elliot""",,XX,XX,proiettore,,
-- ,,,,,,,,,,
-- Palazzina Meccanica,Primo Piano,02-1M,28,"Film ""Interstellar""",,XX,XX,proiettore,,
-- Palazzina Meccanica,Primo Piano,03-1M,28,Lezione presentazione misericordia Humanitas,,X,X,proiettore,,Maurizio...
-- Palazzina Meccanica,Primo Piano,04-1M,28,"Film ""L'ultimo samurai""",,XX,XX,proiettore,,
-- Palazzina Meccanica,Primo Piano,05-1M,28,"Film ""Frankenstein Junior""",,XX,XX,proiettore,,
-- Palazzina Meccanica,Primo Piano,06-1M,27,Torneo di scacchi 1,,XX,XX,,,
-- Palazzina Meccanica,Primo Piano,08-1M,28,"Film ""I guardiani del destino""",,XX,XX,proiettore,,
-- Palazzina Meccanica,Primo Piano,09-1M,28,"Dibattito ludopatia, schedine di calcio",,XX,XX,,,
-- Palazzina Meccanica,Primo Piano,10-1M,27,Musica,,XX,XX,,,
-- ,,,,,,,,,,
-- Prefabbricato Meccanica,Piano Terra,01-PM,26,"Film ""Il gladiatore""",,XX,XX,proiettore,,
-- Prefabbricato Meccanica,Piano Terra,02-PM,26,"Flm ""A Beautiful Mind""",,XX,XX,proiettore,,
-- Prefabbricato Meccanica,Piano Terra,03-PM,26,"Film ""La vita è bella""",,XX,XX,proiettore,,
-- ,,,,,,,,,,
-- Palestra,Palestra Interna,palestra,100,Lezione di Orientamento di Ingegneria,,XX,,proiettore e oscuranti per finestre,,Francesco Grasso
-- Palestra,Palestra Interna,palestra,100,Lezione di Orientamento di Economia e Management,,,XX,proiettore e oscuranti per finestre,,Ilaria Colivicchi
-- Palestra,Sala Ping Pong,sala ping pong,12,torneo ping pong,,XX,XX,,,
-- Palestra,Campo Esterno,palestra esterna,12,torneo calcio a 5,,XX,XX,,,
-- Palestra,Campo Esterno,palestra esterna,12,torneo di basket,,XX,XX,,,
-- ,,,,,,,,,,
-- Est,seminterrato,seminterrato Est,*,Laboratorio di musica,,XX,XX,,,
-- ,,,,,,,,,,
-- ,,,,

-- Adding data to the table event which contains id (autoincrement), name, description, room, zone, floor, minimum_section
-- Then, we will add to the table round_max_users which contains round, event_id (foreign key), max_users

INSERT INTO event (name,
                   description,
                   room,
                   zone,
                   floor,
                   minimum_section)
VALUES ('Dibattito immigrazione, problema o opportunità?',
        'Dibattito immigrazione, problema o opportunità?',
        '05-TW',
        'Terra Ovest',
        'Piano Terra Rialzato',
        0),
       ('Dibattito inclusività e diversità',
        'Dibattito inclusività e diversità',
        '07-TW',
        'Terra Ovest',
        'Piano Terra Rialzato',
        0),
       ('Dibattito giocatori di calcio',
        'Dibattito giocatori di calcio',
        '09-TW',
        'Terra Ovest',
        'Piano Terra Rialzato',
        0),
       ('Dibattito sul progresso tecnologico',
        'Dibattito sul progresso tecnologico',
        '12-TW',
        'Terra Ovest',
        'Piano Terra Rialzato',
        0),
       ('Dibattito politico',
        'Dibattito politico',
        '14-TW',
        'Terra Ovest',
        'Piano Terra Rialzato',
        0),
       ('Dibattito guerra israelo-palestinese',
        'Dibattito guerra israelo-palestinese',
        '16-TW',
        'Terra Ovest',
        'Piano Terra Rialzato',
        0),
       ('Dibattito guerra Ucraina-Russia',
        'Dibattito guerra Ucraina-Russia',
        '18-TW',
        'Terra Ovest',
        'Piano Terra Rialzato',
        0),
       ('Aula studio maturandi 1',
        'Aula studio maturandi 1',
        '07-1W',
        'Ovest',
        'Primo Piano',
        0),
       ('Aula studio maturandi 2',
        'Aula studio maturandi 2',
        '13-1W',
        'Ovest',
        'Primo Piano',
        0),
       ('Film "Il buco"',
        'Film "Il buco"',
        '08-2W',
        'Ovest',
        'Secondo Piano',
        0),
       ('Giochi di carte, porta un mazzo e si fa un torneo 1',
        'Giochi di carte, porta un mazzo e si fa un torneo 1',
        '10-2W',
        'Ovest',
        'Secondo Piano',
        0),
       ('Giochi di carte, porta un mazzo e si fa un torneo 2',
        'Giochi di carte, porta un mazzo e si fa un torneo 2',
        '12-2W',
        'Ovest',
        'Secondo Piano',
        0),
       ('Lezione di produzione musicale',
        'Lezione di produzione musicale',
        '14-2W',
        'Ovest',
        'Secondo Piano',
        0),
       ('Muri creativi',
        'Muri creativi',
        'Corridoio',
        'Terra Centrale',
        'Piano Terra Rialzato',
        0),
       ('Lezione Vab, (Vigilanza Antincendi boschivi), come farne parte',
        'Lezione Vab, (Vigilanza Antincendi boschivi), come farne parte',
        '01-TC',
        'Terra Centrale',
        'Piano Terra Rialzato',
        0),
       ('Enogastronomia, porta del cibo e lo gustiamo insieme',
        'Enogastronomia, porta del cibo e lo gustiamo insieme',
        '07-TC',
        'Terra Centrale',
        'Piano Terra Rialzato',
        0),
       ('Videogiochi, porta un videogioco e ci divertiamo insieme',
        'Videogiochi, porta un videogioco e ci divertiamo insieme',
        '09-TC',
        'Terra Centrale',
        'Piano Terra Rialzato',
        0),
       ('Lezione su sfruttamento ambientale ed animale',
        'Lezione su sfruttamento ambientale ed animale',
        '11-TC',
        'Terra Centrale',
        'Piano Terra Rialzato',
        0),
       ('Lezione Machine learning',
        'Lezione Machine learning',
        '13-TC',
        'Terra Centrale',
        'Piano Terra Rialzato',
        0),
       ('Arti marziali miste teorico e pratico',
        'Arti marziali miste teorico e pratico',
        '13-TC',
        'Terra Centrale',
        'Piano Terra Rialzato',
        0),
       ('Lezione di scrittura barre musicali',
        'Lezione di scrittura barre musicali',
        '08-TE',
        'Terra Est',
        'Piano Terra Rialzato',
        0),
       ('Film "Rush"',
        'Film "Rush"',
        '00-1E',
        'Est',
        'Primo Piano',
        0),
       ('Torneo di FIFA',
        'Torneo di FIFA',
        '01-1E',
        'Est',
        'Primo Piano',
        0),
       ('Film "The Truman show"',
        'Film "The Truman show"',
        '06-1E',
        'Est',
        'Primo Piano',
        0),
       ('Film "Il bambino con il pigiama a righe"',
        'Film "Il bambino con il pigiama a righe"',
        '07-1E',
        'Est',
        'Primo Piano',
        0),
       ('Laboratorio di strumenti musicali',
        'Laboratorio di strumenti musicali',
        '08-1E',
        'Est',
        'Primo Piano',
        0),
       ('Giochi da tavolo',
        'Giochi da tavolo',
        '09-1E',
        'Est',
        'Primo Piano',
        0),
       ('Torneo di scacchi 2',
        'Torneo di scacchi 2',
        '10-1E',
        'Est',
        'Primo Piano',
        0),
       ('Aula di scrittura o lettura',
        'Aula di scrittura o lettura',
        '11-1E',
        'Est',
        'Primo Piano',
        0),
       ('Film "L''attimo fuggente"',
        'Film "L''attimo fuggente"',
        '12-1E',
        'Est',
        'Primo Piano',
        0),
       ('Aula powernap, riposati e recupera le energie',
        'Aula powernap, riposati e recupera le energie',
        '13-1E',
        'Est',
        'Primo Piano',
        0),
       ('Scrittura basi musicali, imparare le note',
        'Scrittura basi musicali, imparare le note',
        '02-2E',
        'Est',
        'Secondo Piano',
        0),
       ('Aula studio non maturandi 1',
        'Aula studio non maturandi 1',
        '03-2E',
        'Est',
        'Secondo Piano',
        0),
       ('Lezione presentazione progetto macchina fotografica',
        'Lezione presentazione progetto macchina fotografica',
        '04-2E',
        'Est',
        'Secondo Piano',
        0),
       ('Lezione sui motori',
        'Lezione sui motori',
        '06-2E',
        'Est',
        'Secondo Piano',
        0),
       ('Film "Non ci resta che piangere"',
        'Film "Non ci resta che piangere"',
        '08-2E',
        'Est',
        'Secondo Piano',
        0),
       ('Aula studio non maturandi 2',
        'Aula studio non maturandi 2',
        '09-2E',
        'Est',
        'Secondo Piano',
        0),
       ('Lezione contro la violenza sulle donne',
        'Lezione contro la violenza sulle donne',
        '10-2E',
        'Est',
        'Secondo Piano',
        0),
       ('Dibattito sulla legalizzazione o meno delle droghe leggere',
        'Dibattito sulla legalizzazione o meno delle droghe leggere',
        '11-2E',
        'Est',
        'Secondo Piano',
        0),
       ('Lezione anime',
        'Lezione anime',
        '12-2E',
        'Est',
        'Secondo Piano',
        0),
       ('Lezione su Bitcoin, Blockchain e Cryptovalute',
        'Lezione su Bitcoin, Blockchain e Cryptovalute',
        '13-2E',
        'Est',
        'Secondo Piano',
        0),
       ('Aula studio non maturandi 3',
        'Aula studio non maturandi 3',
        '14-2E',
        'Est',
        'Secondo Piano',
        0),
       ('Film "Billy Elliot"',
        'Film "Billy Elliot"',
        '15-2E',
        'Est',
        'Secondo Piano',
        0),
       ('Film "Interstellar"',
        'Film "Interstellar"',
        '02-1M',
        'Palazzina Meccanica',
        'Primo Piano',
        0),
       ('Lezione presentazione Misericordia Humanitas',
        'Lezione presentazione Misericordia Humanitas',
        '03-1M',
        'Palazzina Meccanica',
        'Primo Piano',
        0),
       ('Film "L''ultimo Samurai"',
        'Film "L''ultimo Samurai"',
        '04-1M',
        'Palazzina Meccanica',
        'Primo Piano',
        0),
       ('Film "Frankenstein Junior"',
        'Film "Frankenstein Junior"',
        '05-1M',
        'Palazzina Meccanica',
        'Primo Piano',
        0),
       ('Torneo di scacchi 1',
        'Torneo di scacchi 1',
        '06-1M',
        'Palazzina Meccanica',
        'Primo Piano',
        0),
       ('Film "I guardiani del destino"',
        'Film "I guardiani del destino"',
        '08-1M',
        'Palazzina Meccanica',
        'Primo Piano',
        0),
       ('Dibattito ludopatia, schedine di calcio',
        'Dibattito ludopatia, schedine di calcio',
        '09-1M',
        'Palazzina Meccanica',
        'Primo Piano',
        0),
       ('Musica',
        'Musica',
        '10-1M',
        'Palazzina Meccanica',
        'Primo Piano',
        0),
       ('Film "Il gladiatore"',
        'Film "Il gladiatore"',
        '01-PM',
        'Prefabbricato Meccanica',
        'Piano Terra',
        0),
       ('Film "A beautiful mind"',
        'Film "A beautiful mind"',
        '02-PM',
        'Prefabbricato Meccanica',
        'Piano Terra',
        0),
       ('Film "La vita è bella"',
        'Film "La vita è bella"',
        '03-PM',
        'Prefabbricato Meccanica',
        'Piano Terra',
        0),
       ('Lezione di Orientamento di Ingegneria',
        'Lezione di Orientamento di Ingegneria',
        'Palestra',
        'Palestra',
        'Palestra Interna',
        0),
       ('Lezione di Orientamento di Economia e Management',
        'Lezione di Orientamento di Economia e Management',
        'Palestra',
        'Palestra',
        'Palestra Interna',
        0),
       ('Torneo Ping Pong',
        'Torneo Ping Pong',
        'Sala Ping Pong',
        'Palestra',
        'Sala Ping Pong',
        0),
       ('Torneo calcio a 5',
        'Torneo calcio a 5',
        'Palestra esterna',
        'Palestra',
        'Campo Esterno',
        0),
       ('Torneo di basket',
        'Torneo di basket',
        'Palestra esterna',
        'Palestra',
        'Campo Esterno',
        0),
       ('Laboratorio di musica',
        'Laboratorio di musica',
        'seminterrato Est',
        'Est',
        'seminterrato',
        0);


